rad_pointcloud_node:
  ros__parameters:
    use_sim_time: True 
    radiation_topic: "/rad"
    lidar_topic: "/velodyne_points"             
    output_topic: "/rad_pointcloud_accumulated" 
    source_estimate_topic: "/rad_source_estimate"
    sensor_frame: "base_link"             
    map_frame: "map"                      
    save_ply_directory: "/home/brendoncintas/radmon_ws/"
    save_ply_base_name: "rad_cloud"
    attenuation_coefficient_cm: 0.00012   
    min_cpm_threshold: 300.0             
    ray_max_distance: 4.0                
    min_intensity_publish: 1.0            
    voxel_resolution: 0.1                 
    publish_rate: 1.0                     
    tf_lookup_timeout: 0.15               